const ACTIONS = {
    LOGIN: 'LOGIN',
    GET_TOKEN: 'GET_TOKEN',
    GET_USER: 'GET_USER',
    GET_ALL_USERS: 'GET_ALL_USERS',
    CREATE_COURSE: 'CREATE_COURSE',
    FETCH_ALL: 'FETCH_ALL',
    FETCH_ALL_COURSE_BY_USER:'FETCH_ALL_COURSE_BY_USER',
    FETCH_ALL_COURSE_BY_CATEGORIE:'FETCH_ALL_COURSE_BY_CATEGORIE',
    UPDATE_COURSE: 'UPDATE_COURSE',
    DELETE_COURSE: 'DELETE_COURSE',
    CREATE_CATEGORIE: 'CREATE_CATEGORIE',
    FETCH_ALLCATEGORIE: 'FETCH_ALLCATEGORIE',
    UPDATE_CATEGORIE: 'UPDATE_CATEGORIE',
    DELETE_CATEGORIE: 'DELETE_CATEGORIE'
}

export default ACTIONS